//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: ControlEditor.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _PSP_PROJECT_CONTROLEDITOR_BASE_CLASSES_H
#define _PSP_PROJECT_CONTROLEDITOR_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/splitter.h>
#include <wx/panel.h>
#include <wx/scrolwin.h>
#include <wx/bmpbuttn.h>
#include <wx/glcanvas.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class ControlEditorBase : public wxFrame
{
protected:
    wxSplitterWindow* m_splitter157;
    wxPanel* m_splitterPage163;
    wxScrolledWindow* m_scrollWin201;
    wxBitmapButton* m_bmpButton19934;
    wxBitmapButton* m_bmpButton1993;
    wxBitmapButton* m_bmpButton199;
    wxPanel* m_splitterPage175;
    wxGLCanvas* m_glCanvas147;

protected:

public:
    wxBitmapButton* GetBmpButton19934() { return m_bmpButton19934; }
    wxBitmapButton* GetBmpButton1993() { return m_bmpButton1993; }
    wxBitmapButton* GetBmpButton199() { return m_bmpButton199; }
    wxScrolledWindow* GetScrollWin201() { return m_scrollWin201; }
    wxPanel* GetSplitterPage163() { return m_splitterPage163; }
    wxGLCanvas* GetGlCanvas147() { return m_glCanvas147; }
    wxPanel* GetSplitterPage175() { return m_splitterPage175; }
    wxSplitterWindow* GetSplitter157() { return m_splitter157; }
    ControlEditorBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Control editor"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~ControlEditorBase();
};

#endif
