//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: ControlEditor.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "ControlEditorBase.h"


// Declare the bitmap loading function
extern void wxC870InitBitmapResources();

static bool bBitmapLoaded = false;


ControlEditorBase::ControlEditorBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC870InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer3 = new wxBoxSizer(wxHORIZONTAL);
    this->SetSizer(boxSizer3);
    
    m_splitter157 = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxSP_3D);
    m_splitter157->SetSashGravity(0.2);
    m_splitter157->SetMinimumPaneSize(10);
    
    boxSizer3->Add(m_splitter157, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_splitterPage163 = new wxPanel(m_splitter157, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitter157, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    wxBoxSizer* boxSizer169 = new wxBoxSizer(wxHORIZONTAL);
    m_splitterPage163->SetSizer(boxSizer169);
    
    m_scrollWin201 = new wxScrolledWindow(m_splitterPage163, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitterPage163, wxSize(-1,-1)), wxBORDER_SIMPLE|wxHSCROLL|wxVSCROLL);
    m_scrollWin201->SetScrollRate(5, 5);
    
    boxSizer169->Add(m_scrollWin201, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer203 = new wxBoxSizer(wxHORIZONTAL);
    m_scrollWin201->SetSizer(boxSizer203);
    
    m_bmpButton19934 = new wxBitmapButton(m_scrollWin201, wxID_ANY, wxArtProvider::GetBitmap(wxART_FOLDER, wxART_FRAME_ICON, wxDefaultSize), wxDefaultPosition, wxDLG_UNIT(m_scrollWin201, wxSize(-1,-1)), wxBU_AUTODRAW);
    m_bmpButton19934->SetDefault();
    boxSizer203->Add(m_bmpButton19934, 0, wxALL, WXC_FROM_DIP(5));
    
    m_bmpButton1993 = new wxBitmapButton(m_scrollWin201, wxID_ANY, wxArtProvider::GetBitmap(wxART_FOLDER, wxART_FRAME_ICON, wxDefaultSize), wxDefaultPosition, wxDLG_UNIT(m_scrollWin201, wxSize(-1,-1)), wxBU_AUTODRAW);
    m_bmpButton1993->SetDefault();
    boxSizer203->Add(m_bmpButton1993, 0, wxALL, WXC_FROM_DIP(5));
    
    m_bmpButton199 = new wxBitmapButton(m_scrollWin201, wxID_ANY, wxArtProvider::GetBitmap(wxART_FOLDER, wxART_FRAME_ICON, wxDefaultSize), wxDefaultPosition, wxDLG_UNIT(m_scrollWin201, wxSize(-1,-1)), wxBU_AUTODRAW);
    m_bmpButton199->SetDefault();
    boxSizer203->Add(m_bmpButton199, 0, wxALL, WXC_FROM_DIP(5));
    
    m_splitterPage175 = new wxPanel(m_splitter157, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_splitter157, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_splitter157->SplitVertically(m_splitterPage163, m_splitterPage175, 0);
    
    wxBoxSizer* boxSizer177 = new wxBoxSizer(wxVERTICAL);
    m_splitterPage175->SetSizer(boxSizer177);
    
    int *m_glCanvas147Attr = NULL;
    m_glCanvas147 = new wxGLCanvas(m_splitterPage175, wxID_ANY, m_glCanvas147Attr, wxDefaultPosition, wxDLG_UNIT(m_splitterPage175, wxSize(-1,-1)), wxBORDER_SIMPLE);
    wxDELETEA( m_glCanvas147Attr );
    
    boxSizer177->Add(m_glCanvas147, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    SetName(wxT("ControlEditorBase"));
    SetSize(500,300);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
}

ControlEditorBase::~ControlEditorBase()
{
}
