//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: DebugFrame.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _PSP_PROJECT_DEBUGFRAME_BASE_CLASSES_HPP
#define _PSP_PROJECT_DEBUGFRAME_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/richtext/richtextctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class DebugMainFrameBase : public wxFrame
{
protected:
    wxRichTextCtrl* m_richTextCtrlDebugText;

protected:

public:
    wxRichTextCtrl* GetRichTextCtrlDebugText() { return m_richTextCtrlDebugText; }
    DebugMainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Debug text"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxRESIZE_BORDER|wxMINIMIZE_BOX);
    virtual ~DebugMainFrameBase();
};

#endif
