//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: DataReport.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "DataReportBase.h"


// Declare the bitmap loading function
extern void wxC6A63InitBitmapResources();


namespace {
// return the wxBORDER_SIMPLE that matches the current application theme
wxBorder get_border_simple_theme_aware_bit() {
#if wxVERSION_NUMBER >= 3300 && defined(__WXMSW__)
    return wxSystemSettings::GetAppearance().IsDark() ? wxBORDER_SIMPLE : wxBORDER_DEFAULT;
#else
    return wxBORDER_DEFAULT;
#endif
} // get_border_simple_theme_aware_bit
bool bBitmapLoaded = false;
} // namespace


DataReportBase::DataReportBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC6A63InitBitmapResources();
        bBitmapLoaded = true;
    }
    // Set icon(s) to the application/dialog
    wxIconBundle app_icons;
    {
        wxBitmap iconBmp = wxXmlResource::Get()->LoadBitmap(wxT("chart16"));
        wxIcon icn;
        icn.CopyFromBitmap(iconBmp);
        app_icons.AddIcon( icn );
    }
    {
        wxBitmap iconBmp = wxXmlResource::Get()->LoadBitmap(wxT("chart32"));
        wxIcon icn;
        icn.CopyFromBitmap(iconBmp);
        app_icons.AddIcon( icn );
    }
    {
        wxBitmap iconBmp = wxXmlResource::Get()->LoadBitmap(wxT("chart64"));
        wxIcon icn;
        icn.CopyFromBitmap(iconBmp);
        app_icons.AddIcon( icn );
    }
    {
        wxBitmap iconBmp = wxXmlResource::Get()->LoadBitmap(wxT("chart128"));
        wxIcon icn;
        icn.CopyFromBitmap(iconBmp);
        app_icons.AddIcon( icn );
    }
    {
        wxBitmap iconBmp = wxXmlResource::Get()->LoadBitmap(wxT("chart256"));
        wxIcon icn;
        icn.CopyFromBitmap(iconBmp);
        app_icons.AddIcon( icn );
    }
    SetIcons( app_icons );

    
    wxBoxSizer* boxSizerLvl1_1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizerLvl1_1);
    
    wxBoxSizer* boxSizerLvl2_1 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizerLvl1_1->Add(boxSizerLvl2_1, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_notebookDataReport = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxBK_DEFAULT);
    m_notebookDataReport->SetName(wxT("m_notebookDataReport"));
    
    boxSizerLvl2_1->Add(m_notebookDataReport, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelPowerFlowData = new wxPanel(m_notebookDataReport, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookDataReport, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookDataReport->AddPage(m_panelPowerFlowData, _("Power flow data"), false);
    
    wxBoxSizer* boxSizerLvl3_1 = new wxBoxSizer(wxVERTICAL);
    m_panelPowerFlowData->SetSizer(boxSizerLvl3_1);
    
    m_notebookPowerFlow = new wxNotebook(m_panelPowerFlowData, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelPowerFlowData, wxSize(-1,-1)), wxBK_LEFT|wxBK_DEFAULT);
    m_notebookPowerFlow->SetName(wxT("m_notebookPowerFlow"));
    
    boxSizerLvl3_1->Add(m_notebookPowerFlow, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelPowerFlow = new wxPanel(m_notebookPowerFlow, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookPowerFlow, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookPowerFlow->AddPage(m_panelPowerFlow, _("Power flow"), false);
    
    wxBoxSizer* boxSizerLvl4_1 = new wxBoxSizer(wxVERTICAL);
    m_panelPowerFlow->SetSizer(boxSizerLvl4_1);
    
    m_gridPowerFlow = new wxGrid(m_panelPowerFlow, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelPowerFlow, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridPowerFlow->CreateGrid(0, 0);
    m_gridPowerFlow->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridPowerFlow->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridPowerFlow->UseNativeColHeader(true);
    #endif
    m_gridPowerFlow->EnableEditing(true);
    
    boxSizerLvl4_1->Add(m_gridPowerFlow, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelPFBuses = new wxPanel(m_notebookPowerFlow, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookPowerFlow, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookPowerFlow->AddPage(m_panelPFBuses, _("Buses"), false);
    
    wxBoxSizer* boxSizerLvl4_2 = new wxBoxSizer(wxVERTICAL);
    m_panelPFBuses->SetSizer(boxSizerLvl4_2);
    
    m_gridPFBuses = new wxGrid(m_panelPFBuses, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelPFBuses, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridPFBuses->CreateGrid(0, 0);
    m_gridPFBuses->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridPFBuses->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridPFBuses->UseNativeColHeader(true);
    #endif
    m_gridPFBuses->EnableEditing(true);
    
    boxSizerLvl4_2->Add(m_gridPFBuses, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelPFBranches = new wxPanel(m_notebookPowerFlow, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookPowerFlow, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookPowerFlow->AddPage(m_panelPFBranches, _("Branches"), false);
    
    wxBoxSizer* boxSizerLvl4_3 = new wxBoxSizer(wxVERTICAL);
    m_panelPFBranches->SetSizer(boxSizerLvl4_3);
    
    m_gridPFBranches = new wxGrid(m_panelPFBranches, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelPFBranches, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridPFBranches->CreateGrid(0, 0);
    m_gridPFBranches->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridPFBranches->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridPFBranches->UseNativeColHeader(true);
    #endif
    m_gridPFBranches->EnableEditing(true);
    
    boxSizerLvl4_3->Add(m_gridPFBranches, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelFaultData = new wxPanel(m_notebookDataReport, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookDataReport, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookDataReport->AddPage(m_panelFaultData, _("Fault data"), false);
    
    wxBoxSizer* boxSizerLvl3_2 = new wxBoxSizer(wxVERTICAL);
    m_panelFaultData->SetSizer(boxSizerLvl3_2);
    
    m_notebookFault = new wxNotebook(m_panelFaultData, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelFaultData, wxSize(-1,-1)), wxBK_LEFT|wxBK_DEFAULT);
    m_notebookFault->SetName(wxT("m_notebookFault"));
    
    boxSizerLvl3_2->Add(m_notebookFault, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelFault = new wxPanel(m_notebookFault, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookFault, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookFault->AddPage(m_panelFault, _("Fault"), false);
    
    wxBoxSizer* boxSizerLvl4_4 = new wxBoxSizer(wxVERTICAL);
    m_panelFault->SetSizer(boxSizerLvl4_4);
    
    m_gridFault = new wxGrid(m_panelFault, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelFault, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridFault->CreateGrid(0, 0);
    m_gridFault->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridFault->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridFault->UseNativeColHeader(true);
    #endif
    m_gridFault->EnableEditing(true);
    
    boxSizerLvl4_4->Add(m_gridFault, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelFaultBuses = new wxPanel(m_notebookFault, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookFault, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookFault->AddPage(m_panelFaultBuses, _("Buses"), false);
    
    wxBoxSizer* boxSizerLvl4_5 = new wxBoxSizer(wxVERTICAL);
    m_panelFaultBuses->SetSizer(boxSizerLvl4_5);
    
    m_gridFaultBuses = new wxGrid(m_panelFaultBuses, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelFaultBuses, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridFaultBuses->CreateGrid(0, 0);
    m_gridFaultBuses->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridFaultBuses->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridFaultBuses->UseNativeColHeader(true);
    #endif
    m_gridFaultBuses->EnableEditing(true);
    
    boxSizerLvl4_5->Add(m_gridFaultBuses, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelFaultBranches = new wxPanel(m_notebookFault, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookFault, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookFault->AddPage(m_panelFaultBranches, _("Branches"), false);
    
    wxBoxSizer* boxSizerLvl4_6 = new wxBoxSizer(wxVERTICAL);
    m_panelFaultBranches->SetSizer(boxSizerLvl4_6);
    
    m_gridFaultBranches = new wxGrid(m_panelFaultBranches, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelFaultBranches, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridFaultBranches->CreateGrid(0, 0);
    m_gridFaultBranches->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridFaultBranches->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridFaultBranches->UseNativeColHeader(true);
    #endif
    m_gridFaultBranches->EnableEditing(true);
    
    boxSizerLvl4_6->Add(m_gridFaultBranches, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelFaultGenerators = new wxPanel(m_notebookFault, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookFault, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookFault->AddPage(m_panelFaultGenerators, _("Generators"), false);
    
    wxBoxSizer* boxSizerLvl4_118 = new wxBoxSizer(wxVERTICAL);
    m_panelFaultGenerators->SetSizer(boxSizerLvl4_118);
    
    m_gridFaultGenerators = new wxGrid(m_panelFaultGenerators, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelFaultGenerators, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridFaultGenerators->CreateGrid(0, 0);
    m_gridFaultGenerators->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridFaultGenerators->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridFaultGenerators->UseNativeColHeader(true);
    #endif
    m_gridFaultGenerators->EnableEditing(true);
    
    boxSizerLvl4_118->Add(m_gridFaultGenerators, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelHarmonicsData = new wxPanel(m_notebookDataReport, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookDataReport, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookDataReport->AddPage(m_panelHarmonicsData, _("Harmonics data"), false);
    
    wxBoxSizer* boxSizerLvl3_22 = new wxBoxSizer(wxVERTICAL);
    m_panelHarmonicsData->SetSizer(boxSizerLvl3_22);
    
    m_notebookHarmCurrents = new wxNotebook(m_panelHarmonicsData, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelHarmonicsData, wxSize(-1,-1)), wxBK_LEFT|wxBK_DEFAULT);
    m_notebookHarmCurrents->SetName(wxT("m_notebookHarmCurrents"));
    
    boxSizerLvl3_22->Add(m_notebookHarmCurrents, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelHarmCurrents = new wxPanel(m_notebookHarmCurrents, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookHarmCurrents, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookHarmCurrents->AddPage(m_panelHarmCurrents, _("Sources"), false);
    
    wxBoxSizer* boxSizerLvl4_45 = new wxBoxSizer(wxVERTICAL);
    m_panelHarmCurrents->SetSizer(boxSizerLvl4_45);
    
    m_gridHarmCurrents = new wxGrid(m_panelHarmCurrents, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelHarmCurrents, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridHarmCurrents->CreateGrid(0, 0);
    m_gridHarmCurrents->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridHarmCurrents->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridHarmCurrents->UseNativeColHeader(true);
    #endif
    m_gridHarmCurrents->EnableEditing(true);
    
    boxSizerLvl4_45->Add(m_gridHarmCurrents, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelHarmBuses = new wxPanel(m_notebookHarmCurrents, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookHarmCurrents, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookHarmCurrents->AddPage(m_panelHarmBuses, _("Voltages"), false);
    
    wxBoxSizer* boxSizerLvl4_58 = new wxBoxSizer(wxVERTICAL);
    m_panelHarmBuses->SetSizer(boxSizerLvl4_58);
    
    m_gridHarmBuses = new wxGrid(m_panelHarmBuses, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelHarmBuses, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridHarmBuses->CreateGrid(0, 0);
    m_gridHarmBuses->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridHarmBuses->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridHarmBuses->UseNativeColHeader(true);
    #endif
    m_gridHarmBuses->EnableEditing(true);
    
    boxSizerLvl4_58->Add(m_gridHarmBuses, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelHarmBranches = new wxPanel(m_notebookHarmCurrents, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebookHarmCurrents, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebookHarmCurrents->AddPage(m_panelHarmBranches, _("Currents"), false);
    
    wxBoxSizer* boxSizerLvl4_611 = new wxBoxSizer(wxVERTICAL);
    m_panelHarmBranches->SetSizer(boxSizerLvl4_611);
    
    m_gridHarmBranches = new wxGrid(m_panelHarmBranches, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelHarmBranches, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridHarmBranches->CreateGrid(0, 0);
    m_gridHarmBranches->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridHarmBranches->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridHarmBranches->UseNativeColHeader(true);
    #endif
    m_gridHarmBranches->EnableEditing(true);
    
    boxSizerLvl4_611->Add(m_gridHarmBranches, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_toolbar139 = this->CreateToolBar(wxTB_TEXT|wxTB_FLAT, wxID_ANY);
    m_toolbar139->SetToolBitmapSize(wxSize(16,16));
    
    m_toolbar139->AddTool(TOOL_EXPCSV, _("Export CSV"), wxXmlResource::Get()->LoadBitmap(wxT("save16")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_toolbar139->AddTool(TOOL_CLIPBOARD, _("Copy Data"), wxXmlResource::Get()->LoadBitmap(wxT("copy16")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_toolbar139->AddSeparator();
    
    m_staticText146 = new wxStaticText(m_toolbar139, wxID_ANY, _("Font size:"), wxDefaultPosition, wxDLG_UNIT(m_toolbar139, wxSize(-1,-1)), 0);
    m_toolbar139->AddControl(m_staticText146);
    
    wxArrayString m_choiceFontSizeArr;
    m_choiceFontSizeArr.Add(_("8"));
    m_choiceFontSizeArr.Add(_("9"));
    m_choiceFontSizeArr.Add(_("10"));
    m_choiceFontSizeArr.Add(_("11"));
    m_choiceFontSizeArr.Add(_("12"));
    m_choiceFontSizeArr.Add(_("14"));
    m_choiceFontSizeArr.Add(_("16"));
    m_choiceFontSizeArr.Add(_("18"));
    m_choiceFontSizeArr.Add(_("20"));
    m_choiceFontSizeArr.Add(_("22"));
    m_choiceFontSize = new wxChoice(m_toolbar139, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_toolbar139, wxSize(-1,-1)), m_choiceFontSizeArr, 0);
    m_choiceFontSize->SetSelection(2);
    m_toolbar139->AddControl(m_choiceFontSize);
    
    m_staticText1461 = new wxStaticText(m_toolbar139, wxID_ANY, _("Precision:"), wxDefaultPosition, wxDLG_UNIT(m_toolbar139, wxSize(-1,-1)), 0);
    m_toolbar139->AddControl(m_staticText1461);
    
    m_textCtrlPrecision = new wxTextCtrl(m_toolbar139, wxID_ANY, wxT("4"), wxDefaultPosition, wxDLG_UNIT(m_toolbar139, wxSize(50,-1)), wxTE_CENTRE);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlPrecision->SetHint(wxT(""));
    #endif
    m_toolbar139->AddControl(m_textCtrlPrecision);
    m_toolbar139->Realize();
    
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(m_notebookDataReport)){
        wxPersistenceManager::Get().RegisterAndRestore(m_notebookDataReport);
    } else {
        wxPersistenceManager::Get().Restore(m_notebookDataReport);
    }
    #endif
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(m_notebookPowerFlow)){
        wxPersistenceManager::Get().RegisterAndRestore(m_notebookPowerFlow);
    } else {
        wxPersistenceManager::Get().Restore(m_notebookPowerFlow);
    }
    #endif
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(m_notebookFault)){
        wxPersistenceManager::Get().RegisterAndRestore(m_notebookFault);
    } else {
        wxPersistenceManager::Get().Restore(m_notebookFault);
    }
    #endif
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(m_notebookHarmCurrents)){
        wxPersistenceManager::Get().RegisterAndRestore(m_notebookHarmCurrents);
    } else {
        wxPersistenceManager::Get().Restore(m_notebookHarmCurrents);
    }
    #endif
    
    SetName(wxT("DataReportBase"));
    SetMinClientSize(wxSize(500,300));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
    // Connect events
    this->Bind(wxEVT_MOUSEWHEEL, &DataReportBase::OnMouseWheel, this);
    m_notebookDataReport->Bind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnMainNotebookChanged, this);
    m_notebookPowerFlow->Bind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnPFNotebookChanged, this);
    m_gridPowerFlow->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPowerFlowGridChanged, this);
    m_gridPowerFlow->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFKeyDown, this);
    m_gridPFBuses->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPFBusGridChanged, this);
    m_gridPFBuses->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFBusesKeyDown, this);
    m_gridPFBranches->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPFBranchesGridChanged, this);
    m_gridPFBranches->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFBranchesKeyDown, this);
    m_notebookFault->Bind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnFaultNotebookChanged, this);
    m_gridFault->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaulrGridChanged, this);
    m_gridFault->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultKeyDown, this);
    m_gridFaultBuses->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultBusesGridChanged, this);
    m_gridFaultBuses->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultBusesKeyDown, this);
    m_gridFaultBranches->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultBranchesGridChanged, this);
    m_gridFaultBranches->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultBranchesKeyDown, this);
    m_gridFaultGenerators->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultGeneratorsGridChanged, this);
    m_gridFaultGenerators->Bind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultGeneratorsKeyDown, this);
    m_notebookHarmCurrents->Bind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnHarmNotebookChanged, this);
    m_gridHarmCurrents->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmCurrentGridChanged, this);
    m_gridHarmBuses->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmBusesGridChanged, this);
    m_gridHarmBranches->Bind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmBranchesGridChanged, this);
    this->Bind(wxEVT_COMMAND_TOOL_CLICKED, &DataReportBase::ExportCSVButtonClick, this, TOOL_EXPCSV);
    this->Bind(wxEVT_COMMAND_TOOL_CLICKED, &DataReportBase::ClipboardButtonClick, this, TOOL_CLIPBOARD);
    m_choiceFontSize->Bind(wxEVT_COMMAND_CHOICE_SELECTED, &DataReportBase::OnFontSizeSelected, this);
    m_textCtrlPrecision->Bind(wxEVT_COMMAND_TEXT_UPDATED, &DataReportBase::OnTextPrecisionUpdate, this);
    
}

DataReportBase::~DataReportBase()
{
    this->Unbind(wxEVT_MOUSEWHEEL, &DataReportBase::OnMouseWheel, this);
    m_notebookDataReport->Unbind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnMainNotebookChanged, this);
    m_notebookPowerFlow->Unbind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnPFNotebookChanged, this);
    m_gridPowerFlow->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPowerFlowGridChanged, this);
    m_gridPowerFlow->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFKeyDown, this);
    m_gridPFBuses->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPFBusGridChanged, this);
    m_gridPFBuses->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFBusesKeyDown, this);
    m_gridPFBranches->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnPFBranchesGridChanged, this);
    m_gridPFBranches->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridPFBranchesKeyDown, this);
    m_notebookFault->Unbind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnFaultNotebookChanged, this);
    m_gridFault->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaulrGridChanged, this);
    m_gridFault->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultKeyDown, this);
    m_gridFaultBuses->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultBusesGridChanged, this);
    m_gridFaultBuses->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultBusesKeyDown, this);
    m_gridFaultBranches->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultBranchesGridChanged, this);
    m_gridFaultBranches->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultBranchesKeyDown, this);
    m_gridFaultGenerators->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnFaultGeneratorsGridChanged, this);
    m_gridFaultGenerators->Unbind(wxEVT_KEY_DOWN, &DataReportBase::OnGridFaultGeneratorsKeyDown, this);
    m_notebookHarmCurrents->Unbind(wxEVT_COMMAND_NOTEBOOK_PAGE_CHANGED, &DataReportBase::OnHarmNotebookChanged, this);
    m_gridHarmCurrents->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmCurrentGridChanged, this);
    m_gridHarmBuses->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmBusesGridChanged, this);
    m_gridHarmBranches->Unbind(wxEVT_GRID_CELL_CHANGED, &DataReportBase::OnHarmBranchesGridChanged, this);
    this->Unbind(wxEVT_COMMAND_TOOL_CLICKED, &DataReportBase::ExportCSVButtonClick, this, TOOL_EXPCSV);
    this->Unbind(wxEVT_COMMAND_TOOL_CLICKED, &DataReportBase::ClipboardButtonClick, this, TOOL_CLIPBOARD);
    m_choiceFontSize->Unbind(wxEVT_COMMAND_CHOICE_SELECTED, &DataReportBase::OnFontSizeSelected, this);
    m_textCtrlPrecision->Unbind(wxEVT_COMMAND_TEXT_UPDATED, &DataReportBase::OnTextPrecisionUpdate, this);
    
}

StabilityEventListBase::StabilityEventListBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC6A63InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizerLvl1_1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizerLvl1_1);
    
    m_gridStabEventList = new wxGrid(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxWANTS_CHARS);
    m_gridStabEventList->CreateGrid(0, 0);
    m_gridStabEventList->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_gridStabEventList->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_gridStabEventList->UseNativeColHeader(true);
    #endif
    m_gridStabEventList->EnableEditing(true);
    
    boxSizerLvl1_1->Add(m_gridStabEventList, 1, wxEXPAND, WXC_FROM_DIP(5));
    
    m_buttonOK = new wxButton(this, wxID_ANY, _("OK"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizerLvl1_1->Add(m_buttonOK, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, WXC_FROM_DIP(5));
    
    SetName(wxT("StabilityEventListBase"));
    SetSize(wxDLG_UNIT(this, wxSize(500,300)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
    // Connect events
    m_buttonOK->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &StabilityEventListBase::OnOKButtonClick, this);
    
}

StabilityEventListBase::~StabilityEventListBase()
{
    m_buttonOK->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &StabilityEventListBase::OnOKButtonClick, this);
    
}

ExportCSVFormBase::ExportCSVFormBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC6A63InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer151 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer151);
    
    wxStaticBoxSizer* staticBoxSizer155 = new wxStaticBoxSizer( new wxStaticBox(this, wxID_ANY, _("Power flow data")), wxHORIZONTAL);
    
    boxSizer151->Add(staticBoxSizer155, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_checkBoxPFPowerFlow = new wxCheckBox(this, wxID_ANY, _("Power flow"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxPFPowerFlow->SetValue(false);
    
    staticBoxSizer155->Add(m_checkBoxPFPowerFlow, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxPFBuses = new wxCheckBox(this, wxID_ANY, _("Buses"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxPFBuses->SetValue(true);
    
    staticBoxSizer155->Add(m_checkBoxPFBuses, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxPFBranches = new wxCheckBox(this, wxID_ANY, _("Branches"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxPFBranches->SetValue(false);
    
    staticBoxSizer155->Add(m_checkBoxPFBranches, 0, wxALL, WXC_FROM_DIP(5));
    
    wxStaticBoxSizer* staticBoxSizer156 = new wxStaticBoxSizer( new wxStaticBox(this, wxID_ANY, _("Fault data")), wxHORIZONTAL);
    
    boxSizer151->Add(staticBoxSizer156, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_checkBoxCCFault = new wxCheckBox(this, wxID_ANY, _("Fault"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxCCFault->SetValue(false);
    
    staticBoxSizer156->Add(m_checkBoxCCFault, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxCCBuses = new wxCheckBox(this, wxID_ANY, _("Buses"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxCCBuses->SetValue(false);
    
    staticBoxSizer156->Add(m_checkBoxCCBuses, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxCCBranches = new wxCheckBox(this, wxID_ANY, _("Branches"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxCCBranches->SetValue(false);
    
    staticBoxSizer156->Add(m_checkBoxCCBranches, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxCCGenerators = new wxCheckBox(this, wxID_ANY, _("Generators"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxCCGenerators->SetValue(false);
    
    staticBoxSizer156->Add(m_checkBoxCCGenerators, 0, wxALL, WXC_FROM_DIP(5));
    
    wxStaticBoxSizer* staticBoxSizer157 = new wxStaticBoxSizer( new wxStaticBox(this, wxID_ANY, _("Harmonics data")), wxHORIZONTAL);
    
    boxSizer151->Add(staticBoxSizer157, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_checkBoxHarmSources = new wxCheckBox(this, wxID_ANY, _("Sources"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxHarmSources->SetValue(false);
    
    staticBoxSizer157->Add(m_checkBoxHarmSources, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxHarmVoltages = new wxCheckBox(this, wxID_ANY, _("Voltages"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxHarmVoltages->SetValue(false);
    
    staticBoxSizer157->Add(m_checkBoxHarmVoltages, 0, wxALL, WXC_FROM_DIP(5));
    
    m_checkBoxharmCurrents = new wxCheckBox(this, wxID_ANY, _("Currents"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_checkBoxharmCurrents->SetValue(false);
    
    staticBoxSizer157->Add(m_checkBoxharmCurrents, 0, wxALL, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer152 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer151->Add(boxSizer152, 0, wxALL|wxEXPAND|wxALIGN_RIGHT, WXC_FROM_DIP(5));
    
    m_buttonExport = new wxButton(this, wxID_ANY, _("Export selected"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer152->Add(m_buttonExport, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonCancel = new wxButton(this, wxID_ANY, _("Cancel"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    boxSizer152->Add(m_buttonCancel, 0, wxALL, WXC_FROM_DIP(5));
    
    SetName(wxT("ExportCSVFormBase"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
    // Connect events
    m_buttonExport->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &ExportCSVFormBase::OnExportButtonClick, this);
    m_buttonCancel->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &ExportCSVFormBase::OnCancelButtonClick, this);
    
}

ExportCSVFormBase::~ExportCSVFormBase()
{
    m_buttonExport->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &ExportCSVFormBase::OnExportButtonClick, this);
    m_buttonCancel->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &ExportCSVFormBase::OnCancelButtonClick, this);
    
}
