var searchData=
[
  ['sample_0',['Sample',['../struct_sample.html',1,'']]],
  ['shareddata_1',['SharedData',['../struct_shared_data.html',1,'']]],
  ['shunt_2',['Shunt',['../class_shunt.html',1,'']]],
  ['simtestdata_3',['SimTestData',['../struct_sim_test_data.html',1,'']]],
  ['simulationdata_4',['SimulationData',['../struct_simulation_data.html',1,'']]],
  ['simulationssettingsform_5',['SimulationsSettingsForm',['../class_simulations_settings_form.html',1,'']]],
  ['spacestate_6',['SpaceState',['../struct_transfer_function_1_1_space_state.html',1,'TransferFunction']]],
  ['stabilityeventlist_7',['StabilityEventList',['../class_stability_event_list.html',1,'']]],
  ['sum_8',['Sum',['../class_sum.html',1,'']]],
  ['sumform_9',['SumForm',['../class_sum_form.html',1,'']]],
  ['switchingdata_10',['SwitchingData',['../struct_switching_data.html',1,'']]],
  ['switchingform_11',['SwitchingForm',['../class_switching_form.html',1,'']]],
  ['syncgenerator_12',['SyncGenerator',['../class_sync_generator.html',1,'']]],
  ['syncgeneratorelectricaldata_13',['SyncGeneratorElectricalData',['../struct_sync_generator_electrical_data.html',1,'']]],
  ['syncmachineform_14',['SyncMachineForm',['../class_sync_machine_form.html',1,'']]],
  ['syncmachinemodeldata_15',['SyncMachineModelData',['../struct_sync_machine_model_data.html',1,'']]],
  ['syncmotor_16',['SyncMotor',['../class_sync_motor.html',1,'']]],
  ['syncmotorelectricaldata_17',['SyncMotorElectricalData',['../struct_sync_motor_electrical_data.html',1,'']]]
];
