name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ccache -y

      - name: Create ccache directory
        run: powershell -Command "New-Item -ItemType Directory -Force -Path $env:LOCALAPPDATA\\ccache"

      - name: Set CCACHE_DIR
        run: echo "CCACHE_DIR=$env:LOCALAPPDATA\\ccache" >> $env:GITHUB_ENV

      - name: Restore ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: windows-ccache-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            windows-ccache-

      - name: Configure CMake with ccache
        run: cmake -S . -B build -A Win32 \
             -DCMAKE_C_COMPILER_LAUNCHER=ccache \
             -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Show ccache statistics
        run: ccache -s

      - name: Save ccache
        if: success()
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: windows-ccache-${{ hashFiles('CMakeLists.txt') }}
