name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ccache \
            libwxgtk3.2-dev \
            libgtk-3-dev \
            libgl1-mesa-dev
            
      - name: Set up ccache
        run: |
          ccache --max-size=5G
          echo 'export CC="ccache gcc"' >> $GITHUB_ENV
          echo 'export CXX="ccache g++"' >> $GITHUB_ENV
          
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: linux-ccache-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            linux-ccache-
            
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release
        
      - name: Show ccache statistics
        run: ccache -s