name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Configure CMake
        run: cmake -S . -B build -A Win32

      - name: Build with CMake
        run: cmake --build build --config Release
