name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ccache \
            libwxgtk3.2-dev \
            libgtk-3-dev \
            libgl1-mesa-dev \
            libfftw3-dev

      - name: Create ccache directory
        run: mkdir -p ~/.ccache

      - name: Set up ccache
        run: |
          ccache --max-size=5G
          echo "CC=ccache gcc" >> $GITHUB_ENV
          echo "CXX=ccache g++" >> $GITHUB_ENV

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: linux-ccache-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            linux-ccache-

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Show ccache statistics
        run: ccache -s
